/* Write your PL/SQL query statement below */


SELECT 
    TO_CHAR(SELL_DATE,'YYYY-MM-DD') SELL_DATE,
    COUNT(DISTINCT PRODUCT) NUM_SOLD,
    (SELECT LISTAGG(PRODUCT,',') WITHIN GROUP (ORDER BY PRODUCT)
    FROM (SELECT
          DISTINCT SELL_DATE INNER_DATE,
          PRODUCT
          FROM ACTIVITIES 
          )
    WHERE INNER_DATE = OUTER.SELL_DATE
    ) PRODUCTS
FROM ACTIVITIES OUTER
GROUP BY SELL_DATE
ORDER BY SELL_DATE;