/* Write your PL/SQL query statement below */

SELECT TEACHER_ID,COUNT(*) CNT
FROM (SELECT TEACHER_ID,SUBJECT_ID,COUNT(*) CNT1
      FROM TEACHER 
      GROUP BY (TEACHER_ID,SUBJECT_ID))
GROUP BY TEACHER_ID;


