/* Write your PL/SQL query statement below */

SELECT V.CUSTOMER_ID,COUNT(V.VISIT_ID) COUNT_NO_TRANS
FROM VISITS V LEFT OUTER JOIN TRANSACTIONS T
ON(V.VISIT_ID = T.VISIT_ID)
WHERE T.TRANSACTION_ID IS NULL
GROUP BY V.CUSTOMER_ID;

    
